
data:
  train_path: /app/data/train_agreement.xlsx
  validation_path: /app/data/eval_agreement.xlsx
  test_path: /app/data/test_agreement.xlsx

model:
  name: anferico/bert-for-patents # https://huggingface.co/anferico/bert-for-patents 
  num_lables: 4 # {'FUN': 0, 'STR': 1, 'MIX': 2, 'OTH': 3}
  max_length: 512
  checkpoint: '/app/models/bert-for-patents-agreement.ckpt' # used in test.py

optimizer:
  name: Adam
  args:
    lr: 2e-5
    weight_decay: 0.01

scheduler:
  name: StepLR
  step_size: 5  # Reduce LR every 5 epochs
  gamma: 0.1    # Multiply LR by 0.1 at each step

train:
  seed: 1999 # if -1, it generates a random seed internally.
  batch_size: 64
  num_workers: 0 # if 0, data loading is sequential. if > 0 allows parallel loading.
  use_gpu: true
  gpus: 1
  max_epochs: 10
  validate_every: 0.1
  save_dir: '/app/models'
  save_name: 'best-checkpoint'

validation:
  batch_size: 64
  num_workers: 0
  early_stopping: True

test:
  batch_size: 64
  num_workers: 0
  save_dir: '/app/results'
  save_name: 'results_new'

wandb:
  project: patent-sentence-classification